name: SiTS_HC_ML

channels:
  - conda-forge
  - pytorch
  - pypi

dependencies:
  - matplotlib >= 3.6.2
  - numpy >= 1.23.4
  - tqdm >= 4.64.1
  - opencv >= 4.6.0
  - pytorch >= 1.13.0
  - torchvision >= 0.14.0
  - torchaudio >= 0.13.0
  - scipy >= 1.10.1
  - pillow >= 9.4.0
